### ISSUE TITLE
Problem when calling memset on raspi4

### ISSUE THREAD

**Issue by OscarShiang** [DavidSpickett/ARMMultiTasking#25]
Hi, 

I am currently trying to call `memset` to initialize bss section on my raspi4, but found out the board halted as a result. 

After digging into the [implementation of `memset`](https://github.com/ARM-software/optimized-routines/blob/master/string/aarch64/memset.S), I realized that the alignment fault occurred when calling this function.

According to [Armv8-A architecture profile]( https://developer.arm.com/documentation/ddi0487/latest/), when stage 1 address translation is disabled, the memory will be defined as device type (in D5.2.9 section). 
However, any unaligned access to device type memory will cause an alignment fault and halt the board (in B2.5.2 section). 

In current stage, AMT does not enable MMU. Any unaligned access to the memory may cause this fault and freeze the kernel.

Is there any idea to overcome this problem? Or we should turn on the setting for MMU?

**Comment by DavidSpickett** [comment]
I haven't dug into the implementation so I assume that aligning .bss in the linker script isn't enough. Since memset itself will do something unaligned during the course of the copy.

So initialising the MMU would be the way to go. Ideally just to a flat layout that allows unaligned accesses.

**Comment by DavidSpickett** [comment]
Now that Raspi4 has landed I think we can call this fixed.
